version: '3.9'
services:
  backend:
    image: backend:amd64
    ports:
      - "1798:1798"

  frontend:
    image: frontend:amd64
    ports:
      - "3000:80"
    depends_on:
      - backend
  osrm:
    image: osrm/osrm-backend
    command: osrm-routed /data/your-map.osrm
    volumes:
      - ./osrm-data:/data
    ports:
      - "5000:5000"
