/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FlightRouteImport } from './routes/flight'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TripIdRouteImport } from './routes/$tripId'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTripIdIndexRouteImport } from './routes/admin/$tripId/index'
import { Route as AdminTripIdRouteIdRouteImport } from './routes/admin/$tripId/$routeId'

const FlightRoute = FlightRouteImport.update({
  id: '/flight',
  path: '/flight',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIdRoute = TripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTripIdIndexRoute = AdminTripIdIndexRouteImport.update({
  id: '/$tripId/',
  path: '/$tripId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTripIdRouteIdRoute = AdminTripIdRouteIdRouteImport.update({
  id: '/$tripId/$routeId',
  path: '/$tripId/$routeId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$tripId': typeof TripIdRoute
  '/auth': typeof AuthRoute
  '/flight': typeof FlightRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$tripId/$routeId': typeof AdminTripIdRouteIdRoute
  '/admin/$tripId': typeof AdminTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$tripId': typeof TripIdRoute
  '/auth': typeof AuthRoute
  '/flight': typeof FlightRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$tripId/$routeId': typeof AdminTripIdRouteIdRoute
  '/admin/$tripId': typeof AdminTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$tripId': typeof TripIdRoute
  '/auth': typeof AuthRoute
  '/flight': typeof FlightRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$tripId/$routeId': typeof AdminTripIdRouteIdRoute
  '/admin/$tripId/': typeof AdminTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$tripId'
    | '/auth'
    | '/flight'
    | '/admin/'
    | '/admin/$tripId/$routeId'
    | '/admin/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$tripId'
    | '/auth'
    | '/flight'
    | '/admin'
    | '/admin/$tripId/$routeId'
    | '/admin/$tripId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$tripId'
    | '/auth'
    | '/flight'
    | '/admin/'
    | '/admin/$tripId/$routeId'
    | '/admin/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  TripIdRoute: typeof TripIdRoute
  AuthRoute: typeof AuthRoute
  FlightRoute: typeof FlightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/flight': {
      id: '/flight'
      path: '/flight'
      fullPath: '/flight'
      preLoaderRoute: typeof FlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tripId': {
      id: '/$tripId'
      path: '/$tripId'
      fullPath: '/$tripId'
      preLoaderRoute: typeof TripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$tripId/': {
      id: '/admin/$tripId/'
      path: '/$tripId'
      fullPath: '/admin/$tripId'
      preLoaderRoute: typeof AdminTripIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$tripId/$routeId': {
      id: '/admin/$tripId/$routeId'
      path: '/$tripId/$routeId'
      fullPath: '/admin/$tripId/$routeId'
      preLoaderRoute: typeof AdminTripIdRouteIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTripIdRouteIdRoute: typeof AdminTripIdRouteIdRoute
  AdminTripIdIndexRoute: typeof AdminTripIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminTripIdRouteIdRoute: AdminTripIdRouteIdRoute,
  AdminTripIdIndexRoute: AdminTripIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  TripIdRoute: TripIdRoute,
  AuthRoute: AuthRoute,
  FlightRoute: FlightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
